
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE hashes (
id SERIAL PRIMARY KEY,
path VARCHAR(255) UNIQUE NOT NULL,
hash TEXT NOT NULL,
signature BYTEA NOT NULL,
data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
