name: CI - Integrity Checker

on:
  push:
    branches:
      - dev
      - main
      - "feature/**"

  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt || true

      - name: Validar execução básica
        run: |
          python main.py --help